### ISSUE TITLE
XML file invalid: newsdev2021.en-is.hypo.is.xml. It does not validate against the XML Schema

### ISSUE THREAD

**Issue by BrightXiaoHan** [wmt-conference/wmt-format-tools#3]

**Comment by zhoutao1996** [comment]
We meet the same problem——It does not validate against the XML Schema. Did you solved it?

**Comment by BrightXiaoHan** [comment]
You can submit your result via txt format.

**Comment by bhaddow** [comment]
Could you attach the file?

**Comment by BrightXiaoHan** [comment]
I don't know how to attach the whole file to this issue.

**Comment by BrightXiaoHan** [comment]
![newstest2021 src en-zh xml](https://user-images.githubusercontent.com/25839309/121986688-89443000-cdc9-11eb-9d83-ce78bb41b3c7.png)

**Comment by bhaddow** [comment]
OK, could you send me the file at bhaddow@ed.ac.uk ?

**Comment by qiushigui** [comment]
We meet the same problem——It does not validate against the XML Schema. and try to submit a txt file, but the system shows you have no submission

**Comment by qiushigui** [comment]
I can submit my result file success.

**Comment by bhaddow** [comment]
The lang/language confusion was fixed by 2bb83eea , so I will close this issue now.
